ALTER TABLE fleet.fleets
ADD COLUMN IF NOT EXISTS cargo_metal INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS cargo_crystal INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS cargo_gas INTEGER NOT NULL DEFAULT 0;
