ALTER TABLE planet.planets ADD COLUMN IF NOT EXISTS type VARCHAR(20) NOT NULL DEFAULT 'terran';

ALTER TABLE planet.planets ADD COLUMN IF NOT EXISTS temperature INTEGER NOT NULL DEFAULT 20;

ALTER TABLE planet.planets ADD COLUMN IF NOT EXISTS missile_ipms INTEGER NOT NULL DEFAULT 0;

ALTER TABLE planet.planets ADD COLUMN IF NOT EXISTS missile_abms INTEGER NOT NULL DEFAULT 0;
