-- +goose Up
CREATE SCHEMA IF NOT EXISTS planet;

CREATE TABLE IF NOT EXISTS planet.planets (
    id SERIAL PRIMARY KEY,
    user_id INTEGER UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL DEFAULT 'Homeworld',
    galaxy INTEGER NOT NULL DEFAULT 1,
    system INTEGER NOT NULL DEFAULT 1,
    position INTEGER NOT NULL DEFAULT 7,
    metal INTEGER NOT NULL DEFAULT 500,
    crystal INTEGER NOT NULL DEFAULT 300,
    gas INTEGER NOT NULL DEFAULT 200,
    energy INTEGER NOT NULL DEFAULT 50,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- +goose Down
DROP TABLE IF EXISTS planet.planets;
DROP SCHEMA IF EXISTS planet;
